Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
try:
    df = pd.read_csv(url, delimiter=",", encoding='latin-1')
except pd.errors.ParserError as e:
    print(f"Error parsing CSV: {e}")
    # Tindakan yang sesuai, seperti membersihkan atau membuang baris yang bermasalah

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-9b6fa78b8bae>[0m in [0;36m<cell line: 1>[0;34m()[0m
[1;32m      1[0m [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m     [0mdf[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_csv[0m[0;34m([0m[0murl[0m[0;34m,[0m [0mdelimiter[0m[0;34m=[0m[0;34m","[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0;34m'latin-1'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;32mexcept[0m [0mpd[0m[0;34m.[0m[0merrors[0m[0;34m.[0m[0mParserError[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mprint[0m[0;34m([0m[0;34mf"Error parsing CSV: {e}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0;31m# Tindakan yang sesuai, seperti membersihkan atau membuang baris yang bermasalah[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'url' is not defined

